// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package rv_plic_reg_pkg;

  // Param list
  parameter int NumSrc = 53;
  parameter int NumTarget = 2;
  parameter int PrioWidth = 3;
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 26;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio0_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio1_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio2_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio3_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio4_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio5_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio6_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio7_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio8_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio9_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio10_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio11_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio12_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio13_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio14_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio15_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio16_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio17_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio18_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio19_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio20_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio21_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio22_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio23_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio24_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio25_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio26_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio27_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio28_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio29_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio30_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio31_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio32_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio33_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio34_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio35_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio36_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio37_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio38_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio39_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio40_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio41_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio42_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio43_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio44_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio45_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio46_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio47_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio48_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio49_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio50_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio51_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_prio52_reg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_ie0_mreg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_ie1_mreg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_threshold0_reg_t;

  typedef struct packed {
    logic [5:0]  q;
    logic        qe;
    logic        re;
  } rv_plic_reg2hw_cc0_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } rv_plic_reg2hw_threshold1_reg_t;

  typedef struct packed {
    logic [5:0]  q;
    logic        qe;
    logic        re;
  } rv_plic_reg2hw_cc1_reg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_msip0_reg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_msip1_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } rv_plic_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } rv_plic_hw2reg_ip_mreg_t;

  typedef struct packed {
    logic [5:0]  d;
  } rv_plic_hw2reg_cc0_reg_t;

  typedef struct packed {
    logic [5:0]  d;
  } rv_plic_hw2reg_cc1_reg_t;

  // Register -> HW type
  typedef struct packed {
    rv_plic_reg2hw_prio0_reg_t prio0; // [290:288]
    rv_plic_reg2hw_prio1_reg_t prio1; // [287:285]
    rv_plic_reg2hw_prio2_reg_t prio2; // [284:282]
    rv_plic_reg2hw_prio3_reg_t prio3; // [281:279]
    rv_plic_reg2hw_prio4_reg_t prio4; // [278:276]
    rv_plic_reg2hw_prio5_reg_t prio5; // [275:273]
    rv_plic_reg2hw_prio6_reg_t prio6; // [272:270]
    rv_plic_reg2hw_prio7_reg_t prio7; // [269:267]
    rv_plic_reg2hw_prio8_reg_t prio8; // [266:264]
    rv_plic_reg2hw_prio9_reg_t prio9; // [263:261]
    rv_plic_reg2hw_prio10_reg_t prio10; // [260:258]
    rv_plic_reg2hw_prio11_reg_t prio11; // [257:255]
    rv_plic_reg2hw_prio12_reg_t prio12; // [254:252]
    rv_plic_reg2hw_prio13_reg_t prio13; // [251:249]
    rv_plic_reg2hw_prio14_reg_t prio14; // [248:246]
    rv_plic_reg2hw_prio15_reg_t prio15; // [245:243]
    rv_plic_reg2hw_prio16_reg_t prio16; // [242:240]
    rv_plic_reg2hw_prio17_reg_t prio17; // [239:237]
    rv_plic_reg2hw_prio18_reg_t prio18; // [236:234]
    rv_plic_reg2hw_prio19_reg_t prio19; // [233:231]
    rv_plic_reg2hw_prio20_reg_t prio20; // [230:228]
    rv_plic_reg2hw_prio21_reg_t prio21; // [227:225]
    rv_plic_reg2hw_prio22_reg_t prio22; // [224:222]
    rv_plic_reg2hw_prio23_reg_t prio23; // [221:219]
    rv_plic_reg2hw_prio24_reg_t prio24; // [218:216]
    rv_plic_reg2hw_prio25_reg_t prio25; // [215:213]
    rv_plic_reg2hw_prio26_reg_t prio26; // [212:210]
    rv_plic_reg2hw_prio27_reg_t prio27; // [209:207]
    rv_plic_reg2hw_prio28_reg_t prio28; // [206:204]
    rv_plic_reg2hw_prio29_reg_t prio29; // [203:201]
    rv_plic_reg2hw_prio30_reg_t prio30; // [200:198]
    rv_plic_reg2hw_prio31_reg_t prio31; // [197:195]
    rv_plic_reg2hw_prio32_reg_t prio32; // [194:192]
    rv_plic_reg2hw_prio33_reg_t prio33; // [191:189]
    rv_plic_reg2hw_prio34_reg_t prio34; // [188:186]
    rv_plic_reg2hw_prio35_reg_t prio35; // [185:183]
    rv_plic_reg2hw_prio36_reg_t prio36; // [182:180]
    rv_plic_reg2hw_prio37_reg_t prio37; // [179:177]
    rv_plic_reg2hw_prio38_reg_t prio38; // [176:174]
    rv_plic_reg2hw_prio39_reg_t prio39; // [173:171]
    rv_plic_reg2hw_prio40_reg_t prio40; // [170:168]
    rv_plic_reg2hw_prio41_reg_t prio41; // [167:165]
    rv_plic_reg2hw_prio42_reg_t prio42; // [164:162]
    rv_plic_reg2hw_prio43_reg_t prio43; // [161:159]
    rv_plic_reg2hw_prio44_reg_t prio44; // [158:156]
    rv_plic_reg2hw_prio45_reg_t prio45; // [155:153]
    rv_plic_reg2hw_prio46_reg_t prio46; // [152:150]
    rv_plic_reg2hw_prio47_reg_t prio47; // [149:147]
    rv_plic_reg2hw_prio48_reg_t prio48; // [146:144]
    rv_plic_reg2hw_prio49_reg_t prio49; // [143:141]
    rv_plic_reg2hw_prio50_reg_t prio50; // [140:138]
    rv_plic_reg2hw_prio51_reg_t prio51; // [137:135]
    rv_plic_reg2hw_prio52_reg_t prio52; // [134:132]
    rv_plic_reg2hw_ie0_mreg_t [52:0] ie0; // [131:79]
    rv_plic_reg2hw_ie1_mreg_t [52:0] ie1; // [78:26]
    rv_plic_reg2hw_threshold0_reg_t threshold0; // [25:23]
    rv_plic_reg2hw_cc0_reg_t cc0; // [22:15]
    rv_plic_reg2hw_threshold1_reg_t threshold1; // [14:12]
    rv_plic_reg2hw_cc1_reg_t cc1; // [11:4]
    rv_plic_reg2hw_msip0_reg_t msip0; // [3:3]
    rv_plic_reg2hw_msip1_reg_t msip1; // [2:2]
    rv_plic_reg2hw_alert_test_reg_t alert_test; // [1:0]
  } rv_plic_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    rv_plic_hw2reg_ip_mreg_t [52:0] ip; // [117:12]
    rv_plic_hw2reg_cc0_reg_t cc0; // [11:6]
    rv_plic_hw2reg_cc1_reg_t cc1; // [5:0]
  } rv_plic_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO0_OFFSET = 27'h 0;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO1_OFFSET = 27'h 4;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO2_OFFSET = 27'h 8;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO3_OFFSET = 27'h c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO4_OFFSET = 27'h 10;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO5_OFFSET = 27'h 14;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO6_OFFSET = 27'h 18;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO7_OFFSET = 27'h 1c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO8_OFFSET = 27'h 20;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO9_OFFSET = 27'h 24;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO10_OFFSET = 27'h 28;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO11_OFFSET = 27'h 2c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO12_OFFSET = 27'h 30;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO13_OFFSET = 27'h 34;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO14_OFFSET = 27'h 38;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO15_OFFSET = 27'h 3c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO16_OFFSET = 27'h 40;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO17_OFFSET = 27'h 44;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO18_OFFSET = 27'h 48;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO19_OFFSET = 27'h 4c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO20_OFFSET = 27'h 50;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO21_OFFSET = 27'h 54;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO22_OFFSET = 27'h 58;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO23_OFFSET = 27'h 5c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO24_OFFSET = 27'h 60;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO25_OFFSET = 27'h 64;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO26_OFFSET = 27'h 68;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO27_OFFSET = 27'h 6c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO28_OFFSET = 27'h 70;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO29_OFFSET = 27'h 74;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO30_OFFSET = 27'h 78;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO31_OFFSET = 27'h 7c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO32_OFFSET = 27'h 80;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO33_OFFSET = 27'h 84;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO34_OFFSET = 27'h 88;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO35_OFFSET = 27'h 8c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO36_OFFSET = 27'h 90;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO37_OFFSET = 27'h 94;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO38_OFFSET = 27'h 98;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO39_OFFSET = 27'h 9c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO40_OFFSET = 27'h a0;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO41_OFFSET = 27'h a4;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO42_OFFSET = 27'h a8;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO43_OFFSET = 27'h ac;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO44_OFFSET = 27'h b0;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO45_OFFSET = 27'h b4;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO46_OFFSET = 27'h b8;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO47_OFFSET = 27'h bc;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO48_OFFSET = 27'h c0;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO49_OFFSET = 27'h c4;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO50_OFFSET = 27'h c8;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO51_OFFSET = 27'h cc;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO52_OFFSET = 27'h d0;
  parameter logic [BlockAw-1:0] RV_PLIC_IP_0_OFFSET = 27'h 1000;
  parameter logic [BlockAw-1:0] RV_PLIC_IP_1_OFFSET = 27'h 1004;
  parameter logic [BlockAw-1:0] RV_PLIC_IE0_0_OFFSET = 27'h 2000;
  parameter logic [BlockAw-1:0] RV_PLIC_IE0_1_OFFSET = 27'h 2004;
  parameter logic [BlockAw-1:0] RV_PLIC_IE1_0_OFFSET = 27'h 2100;
  parameter logic [BlockAw-1:0] RV_PLIC_IE1_1_OFFSET = 27'h 2104;
  parameter logic [BlockAw-1:0] RV_PLIC_THRESHOLD0_OFFSET = 27'h 200000;
  parameter logic [BlockAw-1:0] RV_PLIC_CC0_OFFSET = 27'h 200004;
  parameter logic [BlockAw-1:0] RV_PLIC_THRESHOLD1_OFFSET = 27'h 201000;
  parameter logic [BlockAw-1:0] RV_PLIC_CC1_OFFSET = 27'h 201004;
  parameter logic [BlockAw-1:0] RV_PLIC_MSIP0_OFFSET = 27'h 4000000;
  parameter logic [BlockAw-1:0] RV_PLIC_MSIP1_OFFSET = 27'h 4000004;
  parameter logic [BlockAw-1:0] RV_PLIC_ALERT_TEST_OFFSET = 27'h 4004000;

  // Reset values for hwext registers and their fields
  parameter logic [5:0] RV_PLIC_CC0_RESVAL = 6'h 0;
  parameter logic [5:0] RV_PLIC_CC1_RESVAL = 6'h 0;
  parameter logic [0:0] RV_PLIC_ALERT_TEST_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    RV_PLIC_PRIO0,
    RV_PLIC_PRIO1,
    RV_PLIC_PRIO2,
    RV_PLIC_PRIO3,
    RV_PLIC_PRIO4,
    RV_PLIC_PRIO5,
    RV_PLIC_PRIO6,
    RV_PLIC_PRIO7,
    RV_PLIC_PRIO8,
    RV_PLIC_PRIO9,
    RV_PLIC_PRIO10,
    RV_PLIC_PRIO11,
    RV_PLIC_PRIO12,
    RV_PLIC_PRIO13,
    RV_PLIC_PRIO14,
    RV_PLIC_PRIO15,
    RV_PLIC_PRIO16,
    RV_PLIC_PRIO17,
    RV_PLIC_PRIO18,
    RV_PLIC_PRIO19,
    RV_PLIC_PRIO20,
    RV_PLIC_PRIO21,
    RV_PLIC_PRIO22,
    RV_PLIC_PRIO23,
    RV_PLIC_PRIO24,
    RV_PLIC_PRIO25,
    RV_PLIC_PRIO26,
    RV_PLIC_PRIO27,
    RV_PLIC_PRIO28,
    RV_PLIC_PRIO29,
    RV_PLIC_PRIO30,
    RV_PLIC_PRIO31,
    RV_PLIC_PRIO32,
    RV_PLIC_PRIO33,
    RV_PLIC_PRIO34,
    RV_PLIC_PRIO35,
    RV_PLIC_PRIO36,
    RV_PLIC_PRIO37,
    RV_PLIC_PRIO38,
    RV_PLIC_PRIO39,
    RV_PLIC_PRIO40,
    RV_PLIC_PRIO41,
    RV_PLIC_PRIO42,
    RV_PLIC_PRIO43,
    RV_PLIC_PRIO44,
    RV_PLIC_PRIO45,
    RV_PLIC_PRIO46,
    RV_PLIC_PRIO47,
    RV_PLIC_PRIO48,
    RV_PLIC_PRIO49,
    RV_PLIC_PRIO50,
    RV_PLIC_PRIO51,
    RV_PLIC_PRIO52,
    RV_PLIC_IP_0,
    RV_PLIC_IP_1,
    RV_PLIC_IE0_0,
    RV_PLIC_IE0_1,
    RV_PLIC_IE1_0,
    RV_PLIC_IE1_1,
    RV_PLIC_THRESHOLD0,
    RV_PLIC_CC0,
    RV_PLIC_THRESHOLD1,
    RV_PLIC_CC1,
    RV_PLIC_MSIP0,
    RV_PLIC_MSIP1,
    RV_PLIC_ALERT_TEST
  } rv_plic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] RV_PLIC_PERMIT [66] = '{
    4'b 0001, // index[ 0] RV_PLIC_PRIO0
    4'b 0001, // index[ 1] RV_PLIC_PRIO1
    4'b 0001, // index[ 2] RV_PLIC_PRIO2
    4'b 0001, // index[ 3] RV_PLIC_PRIO3
    4'b 0001, // index[ 4] RV_PLIC_PRIO4
    4'b 0001, // index[ 5] RV_PLIC_PRIO5
    4'b 0001, // index[ 6] RV_PLIC_PRIO6
    4'b 0001, // index[ 7] RV_PLIC_PRIO7
    4'b 0001, // index[ 8] RV_PLIC_PRIO8
    4'b 0001, // index[ 9] RV_PLIC_PRIO9
    4'b 0001, // index[10] RV_PLIC_PRIO10
    4'b 0001, // index[11] RV_PLIC_PRIO11
    4'b 0001, // index[12] RV_PLIC_PRIO12
    4'b 0001, // index[13] RV_PLIC_PRIO13
    4'b 0001, // index[14] RV_PLIC_PRIO14
    4'b 0001, // index[15] RV_PLIC_PRIO15
    4'b 0001, // index[16] RV_PLIC_PRIO16
    4'b 0001, // index[17] RV_PLIC_PRIO17
    4'b 0001, // index[18] RV_PLIC_PRIO18
    4'b 0001, // index[19] RV_PLIC_PRIO19
    4'b 0001, // index[20] RV_PLIC_PRIO20
    4'b 0001, // index[21] RV_PLIC_PRIO21
    4'b 0001, // index[22] RV_PLIC_PRIO22
    4'b 0001, // index[23] RV_PLIC_PRIO23
    4'b 0001, // index[24] RV_PLIC_PRIO24
    4'b 0001, // index[25] RV_PLIC_PRIO25
    4'b 0001, // index[26] RV_PLIC_PRIO26
    4'b 0001, // index[27] RV_PLIC_PRIO27
    4'b 0001, // index[28] RV_PLIC_PRIO28
    4'b 0001, // index[29] RV_PLIC_PRIO29
    4'b 0001, // index[30] RV_PLIC_PRIO30
    4'b 0001, // index[31] RV_PLIC_PRIO31
    4'b 0001, // index[32] RV_PLIC_PRIO32
    4'b 0001, // index[33] RV_PLIC_PRIO33
    4'b 0001, // index[34] RV_PLIC_PRIO34
    4'b 0001, // index[35] RV_PLIC_PRIO35
    4'b 0001, // index[36] RV_PLIC_PRIO36
    4'b 0001, // index[37] RV_PLIC_PRIO37
    4'b 0001, // index[38] RV_PLIC_PRIO38
    4'b 0001, // index[39] RV_PLIC_PRIO39
    4'b 0001, // index[40] RV_PLIC_PRIO40
    4'b 0001, // index[41] RV_PLIC_PRIO41
    4'b 0001, // index[42] RV_PLIC_PRIO42
    4'b 0001, // index[43] RV_PLIC_PRIO43
    4'b 0001, // index[44] RV_PLIC_PRIO44
    4'b 0001, // index[45] RV_PLIC_PRIO45
    4'b 0001, // index[46] RV_PLIC_PRIO46
    4'b 0001, // index[47] RV_PLIC_PRIO47
    4'b 0001, // index[48] RV_PLIC_PRIO48
    4'b 0001, // index[49] RV_PLIC_PRIO49
    4'b 0001, // index[50] RV_PLIC_PRIO50
    4'b 0001, // index[51] RV_PLIC_PRIO51
    4'b 0001, // index[52] RV_PLIC_PRIO52
    4'b 1111, // index[53] RV_PLIC_IP_0
    4'b 0111, // index[54] RV_PLIC_IP_1
    4'b 1111, // index[55] RV_PLIC_IE0_0
    4'b 0111, // index[56] RV_PLIC_IE0_1
    4'b 1111, // index[57] RV_PLIC_IE1_0
    4'b 0111, // index[58] RV_PLIC_IE1_1
    4'b 0001, // index[59] RV_PLIC_THRESHOLD0
    4'b 0001, // index[60] RV_PLIC_CC0
    4'b 0001, // index[61] RV_PLIC_THRESHOLD1
    4'b 0001, // index[62] RV_PLIC_CC1
    4'b 0001, // index[63] RV_PLIC_MSIP0
    4'b 0001, // index[64] RV_PLIC_MSIP1
    4'b 0001  // index[65] RV_PLIC_ALERT_TEST
  };

endpackage

